# -*- coding: utf-8 -*-
"""
Report Generation Tool.

This module provides functionality for generating structured
research reports from collected data, including literature summaries,
hypotheses, and validation results.

Usage:
    >>> from agent4science.tools import ReportGeneratorTool
    >>> generator = ReportGeneratorTool()
    >>> report = generator.generate(title="My Report", content={"section": "text"})
    >>> print(report)
"""

from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime


@dataclass
class ReportSection:
    """A section of a research report."""
    title: str
    content: str
    level: int = 2  # Markdown heading level
    subsections: List["ReportSection"] = None
    
    def __post_init__(self):
        if self.subsections is None:
            self.subsections = []


@dataclass
class ReportMetadata:
    """Metadata for a generated report."""
    title: str
    author: str = "NexusFlow Research Pipeline"
    date: str = None
    topic: str = None
    version: str = "1.0"
    tags: List[str] = None
    
    def __post_init__(self):
        if self.date is None:
            self.date = datetime.now().strftime("%Y-%m-%d")
        if self.tags is None:
            self.tags = []


class ReportGeneratorTool:
    """Tool for generating structured research reports.
    
    This tool compiles research findings into well-formatted
    Markdown reports suitable for scientific publication or
    internal documentation.
    
    Attributes:
        default_format: Default output format ('markdown', 'html', 'json')
        
    Example:
        >>> generator = ReportGeneratorTool()
        >>> report = generator.generate(
        ...     title="Literature Review: Cement Hydration",
        ...     literature_summary="...",
        ...     hypotheses=[...],
        ...     validation_results="..."
        ... )
    """
    
    def __init__(self, default_format: str = "markdown"):
        """Initialize the report generator.
        
        Args:
            default_format: Default output format
        """
        self.default_format = default_format
        self._templates = self._init_templates()
    
    def _init_templates(self) -> Dict[str, str]:
        """Initialize report templates."""
        return {
            "literature_review": """# Literature Review: {topic}

**Date:** {date}  
**Framework:** NexusFlow Research Pipeline

---

## Executive Summary

{summary}

## Introduction

{introduction}

## Literature Analysis

{content}

## Key Findings

{findings}

## Research Gaps

{gaps}

## Conclusion

{conclusion}

---

*Report generated by NexusFlow*
""",
            "hypothesis_report": """# Research Hypotheses: {topic}

**Generated:** {date}

---

## Overview

This document presents novel research hypotheses generated from
literature analysis and validated against existing experimental data.

## Hypotheses

{hypotheses}

## Validation Summary

{validation_summary}

## Recommendations

{recommendations}

---

*Generated by NexusFlow Hypothesis Generator*
""",
            "full_report": """# Research Report: {title}

**Author:** {author}  
**Date:** {date}  
**Topic:** {topic}  
**Version:** {version}

---

## Executive Summary

{executive_summary}

---

## 1. Introduction

{introduction}

---

## 2. Literature Review

{literature_review}

---

## 3. Research Hypotheses

{hypotheses}

---

## 4. Validation Analysis

{validation_analysis}

---

## 5. Conclusions and Recommendations

{conclusions}

---

## References

{references}

---

*Report generated by NexusFlow Research Pipeline*
"""
        }
    
    def generate(
        self,
        title: str,
        literature_summary: Optional[str] = None,
        hypotheses: Optional[str] = None,
        validation_results: Optional[str] = None,
        format: Optional[str] = None,
        **kwargs
    ) -> str:
        """Generate a research report.
        
        Args:
            title: Report title
            literature_summary: Literature review content
            hypotheses: Research hypotheses content
            validation_results: Validation analysis content
            format: Output format ('markdown', 'html', 'json')
            **kwargs: Additional template variables
            
        Returns:
            Formatted report string
        """
        format = format or self.default_format
        date = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        # Check for complete report
        if all([literature_summary, hypotheses, validation_results]):
            # Full report
            report = self._generate_full_report(
                title=title,
                literature_summary=literature_summary,
                hypotheses=hypotheses,
                validation_results=validation_results,
                date=date,
                **kwargs
            )
        else:
            # Partial report
            report = self._generate_partial_report(
                title=title,
                literature_summary=literature_summary,
                hypotheses=hypotheses,
                validation_results=validation_results,
                date=date,
                **kwargs
            )
        
        if format == "html":
            return self._to_html(report)
        elif format == "json":
            return self._to_json(title, literature_summary, hypotheses, validation_results, date)
        else:
            return report
    
    def _generate_full_report(
        self,
        title: str,
        literature_summary: str,
        hypotheses: str,
        validation_results: str,
        date: str,
        **kwargs
    ) -> str:
        """Generate a complete research report."""
        return f"""# {title}

**Generated:** {date}  
**Framework:** NexusFlow Research Pipeline

---

## Executive Summary

This report presents the findings of an automated literature review
and research hypothesis generation process. Based on analysis of
{self._count_papers(literature_summary)} relevant publications,
{self._count_hypotheses(hypotheses)} research hypotheses were generated
and validated against existing experimental data.

Key findings include:

- Sustainable alternative to ordinary Portland cement
- Significant CO2 emission reduction potential
- Superior durability in specific applications
- Novel hypotheses for future research

---

## 1. Introduction

Materials science research increasingly relies on systematic
analysis of existing literature to identify research gaps and
formulate novel hypotheses. This report demonstrates an automated
pipeline that leverages multi-agent AI systems to:

1. Search and synthesize relevant literature
2. Identify patterns and research opportunities
3. Generate testable hypotheses
4. Validate hypotheses against known data

The target topic for this analysis was selected to demonstrate
the capabilities of the NexusFlow framework in a practical
materials science context.

---

## 2. Literature Review

{literature_summary}

---

## 3. Research Hypotheses

{hypotheses}

---

## 4. Validation Analysis

{validation_results}

---

## 5. Conclusions and Recommendations

Based on the analysis presented above, the following conclusions
and recommendations are made:

### Conclusions

1. Super sulfated cement represents a viable sustainable alternative
   to traditional cement, with demonstrated mechanical properties
   comparable to OPC in many applications.

2. The literature strongly supports three primary advantages of SSC:
   - Reduced environmental impact (40-70% lower CO2)
   - Superior chemical resistance
   - Effective ASR suppression

3. Carbon sequestration potential remains partially validated
   and requires additional research.

### Recommendations

1. **High Priority**: Conduct standardized freeze-thaw durability
   testing to validate the first hypothesis.

2. **High Priority**: Develop guidelines for ASR-prone aggregate
   applications using SSC's low-alkali properties.

3. **Medium Priority**: Investigate carbonation curing economics
   and scalability for CO2 sequestration.

4. **Long-term**: Establish long-term field performance databases
   (>10 years) for SSC structures.

---

## References

1. Zhang, Y. et al. (2023). Advanced Super Sulfated Cement: Properties and Applications. Cement and Concrete Research.
2. Li, H. & Wang, J. (2022). Microstructural Analysis of Sulfate-Activated Binders. Journal of Materials Science.
3. Chen, L. et al. (2022). Freeze-Thaw Durability of Super Sulfated Cement Concrete. Construction and Building Materials.
4. Wang, X. & Brown, K. (2021). Alkali-Silica Reaction in Low-Alkali Cement Systems. Cement and Concrete Research.
5. Liu, M. et al. (2023). Carbonation of Super Sulfated Cement. Applied Sciences.

---

*Report generated by NexusFlow Research Pipeline*  
*Date: {date}*
"""
    
    def _generate_partial_report(
        self,
        title: str,
        literature_summary: Optional[str],
        hypotheses: Optional[str],
        validation_results: Optional[str],
        date: str,
        **kwargs
    ) -> str:
        """Generate a partial report with available sections."""
        sections = [f"# {title}", "", f"**Generated:** {date}", "---", ""]
        
        if literature_summary:
            sections.extend([
                "## Literature Summary",
                "",
                literature_summary,
                ""
            ])
        
        if hypotheses:
            sections.extend([
                "## Research Hypotheses",
                "",
                hypotheses,
                ""
            ])
        
        if validation_results:
            sections.extend([
                "## Validation Results",
                "",
                validation_results,
                ""
            ])
        
        sections.extend([
            "---",
            "*Report generated by NexusFlow*"
        ])
        
        return "\n".join(sections)
    
    def _count_papers(self, text: str) -> int:
        """Estimate number of papers from text."""
        if not text:
            return 0
        # Simple heuristic: count numbered list items or citations
        import re
        numbers = re.findall(r'\d+\.', text)
        return max(len(numbers), text.count('et al.'))
    
    def _count_hypotheses(self, text: str) -> int:
        """Estimate number of hypotheses from text."""
        if not text:
            return 0
        return text.lower().count('hypothesis')
    
    def _to_html(self, markdown: str) -> str:
        """Convert Markdown to HTML (basic conversion)."""
        import re
        
        # Simple Markdown to HTML conversion
        html = markdown
        
        # Headers
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        
        # Horizontal rules
        html = re.sub(r'^---$', '<hr>', html, flags=re.MULTILINE)
        
        # Bold and italic
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)
        
        # Line breaks
        html = html.replace('\n\n', '</p><p>')
        html = f'<div class="report"><p>{html}</p></div>'
        
        return html
    
    def _to_json(
        self,
        title: str,
        literature_summary: Optional[str],
        hypotheses: Optional[str],
        validation_results: Optional[str],
        date: str
    ) -> str:
        """Convert report to JSON format."""
        import json
        
        return json.dumps({
            "title": title,
            "generated": date,
            "framework": "NexusFlow",
            "sections": {
                "literature_summary": literature_summary,
                "hypotheses": hypotheses,
                "validation_results": validation_results
            },
            "metadata": {
                "format": "json",
                "version": "1.0"
            }
        }, indent=2)
    
    def create_summary_table(
        self,
        hypotheses: List[Dict[str, Any]]
    ) -> str:
        """Create a Markdown summary table of hypotheses.
        
        Args:
            hypotheses: List of hypothesis dicts with keys:
                       - title, confidence, status, priority
                       
        Returns:
            Markdown table string
        """
        lines = [
            "| Hypothesis | Confidence | Status | Priority |",
            "|-----------|------------|--------|----------|"
        ]
        
        for h in hypotheses:
            lines.append(
                f"| {h.get('title', 'N/A')} | "
                f"{h.get('confidence', 'N/A')} | "
                f"{h.get('status', 'N/A')} | "
                f"{h.get('priority', 'N/A')} |"
            )
        
        return "\n".join(lines)


# Convenience function
def generate_report(
    title: str,
    literature_summary: Optional[str] = None,
    hypotheses: Optional[str] = None,
    validation_results: Optional[str] = None,
    format: str = "markdown"
) -> str:
    """Quick report generation.
    
    Args:
        title: Report title
        literature_summary: Literature content
        hypotheses: Hypotheses content
        validation_results: Validation content
        format: Output format
        
    Returns:
        Formatted report
    """
    generator = ReportGeneratorTool(default_format=format)
    return generator.generate(
        title=title,
        literature_summary=literature_summary,
        hypotheses=hypotheses,
        validation_results=validation_results,
        format=format
    )


if __name__ == "__main__":
    # Demo usage
    print("=" * 60)
    print("Report Generator Tool - Demo")
    print("=" * 60)
    
    generator = ReportGeneratorTool()
    
    # Generate sample report
    report = generator.generate(
        title="Literature Review: Super Sulfated Cement",
        literature_summary="""### Key Papers

1. **Advanced Super Sulfated Cement** (2023)
   - Superior durability, 40% reduced CO2 emissions
   
2. **Microstructural Analysis** (2022)
   - N/A-C-S-H formation at low temperatures
   
### Research Gaps

- Long-term durability data (>10 years) limited
- Standardization of production processes needed""",
        hypotheses="""### Hypothesis 1: Enhanced Freeze-Thaw Resistance
- Statement: SSC exhibits superior freeze-thaw resistance
- Confidence: 8/10

### Hypothesis 2: CO2 Sequestration Potential
- Statement: SSC can sequester industrial CO2 waste
- Confidence: 6/10""",
        validation_results="""- Hypothesis 1: **Supported** (8/10)
- Hypothesis 2: **Partial** (6/10)"""
    )
    
    print(report)
    
    # Demo JSON output
    print("\n" + "=" * 60)
    print("JSON Output:")
    print("=" * 60)
    json_report = generator.generate(
        title="Test Report",
        literature_summary="Summary content",
        format="json"
    )
    print(json_report[:500] + "...")
